[package]
name = "rut"
version = "0.1.0"
authors = ["Todd Taomae <ttaomae@gmail.com>"]
edition = "2018"

[dependencies]
clap = "~2.33.1"
regex = "~1.3.9"
itertools = "~0.9.0"

[dev-dependencies]
assert_cmd = "1.0.1"
